use Mix.Config

# For production, don't forget to configure the url host to something meaningful, Phoenix
# uses this information when generating URLs.
#
# Note we also include the path to a cache manifest containing the digested version of
# static files. This manifest is generated by the `mix phx.digest` task, which you should
# run after static files are built and before starting your production server.
#
# `:keyfile` and `:certfile` expect an absolute path to the key and cert in disk or a
# relative path inside priv, for example "priv/ssl/server.key". For all supported SSL
# configuration options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1

# endpoint configuration
config :portfolio, PortfolioWeb.Endpoint,
  url: [host: System.get_env("RENDER_EXTERNAL_HOSTNAME") || "drewfravert.local", port: 80],
  # https: [
  #   port: 443,
  #   cipher_suite: :strong,
  #   keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
  #   certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
  #   transport_options: [socket_opts: [:inet6]]
  # ],
  # force_ssl: [hsts: true],
  cache_static_manifest: "priv/static/cache_manifest.json"

# do not print debug messages in production
config :logger, level: :info

# import secrets and configuration from environment variables
# import_config "prod.secret.exs"
